/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Hora;
import javax.swing.JOptionPane;

/**
 *
 * @author baltamar
 */
public class Principal extends javax.swing.JFrame {
    
    Hora hora1;
    Hora hora2;
    Hora hora3;
    
    public Principal() {
        initComponents();
        cmdValidarHora1.setEnabled(false);
        cmdValidarHora2.setEnabled(false);
        cmdCompararHoras.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMinutos1 = new javax.swing.JTextField();
        txtSegundos1 = new javax.swing.JTextField();
        txtHora1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMinutos2 = new javax.swing.JTextField();
        txtSegundos2 = new javax.swing.JTextField();
        txtHora2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cmdBorrar = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        cmdValidarHora1 = new javax.swing.JButton();
        cmdValidarHora2 = new javax.swing.JButton();
        cmdCompararHoras = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("COMPARADOR DE HORAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Horas");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel9.setText("Minutos");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel10.setText("Segundos");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        txtMinutos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinutos1KeyTyped(evt);
            }
        });
        jPanel4.add(txtMinutos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 40, 30));

        txtSegundos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegundos1KeyTyped(evt);
            }
        });
        jPanel4.add(txtSegundos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 40, 30));

        txtHora1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHora1KeyTyped(evt);
            }
        });
        jPanel4.add(txtHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 40, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 220, 110));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Horas");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel12.setText("Minutos");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel13.setText("Segundos");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        txtMinutos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinutos2KeyTyped(evt);
            }
        });
        jPanel5.add(txtMinutos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 40, 30));

        txtSegundos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegundos2KeyTyped(evt);
            }
        });
        jPanel5.add(txtSegundos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 40, 30));

        txtHora2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHora2KeyTyped(evt);
            }
        });
        jPanel5.add(txtHora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 40, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 220, 110));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 70, -1));

        cmdGuardar.setText("Guardar Horas");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, -1));

        cmdValidarHora1.setText("Validar hora1");
        cmdValidarHora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdValidarHora1ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdValidarHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        cmdValidarHora2.setText("Validar hora2");
        cmdValidarHora2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdValidarHora2ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdValidarHora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        cmdCompararHoras.setText("Comparar Horas");
        cmdCompararHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCompararHorasActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCompararHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 230, 150));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultados.setEditable(false);
        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        txtResultados.setAutoscrolls(false);
        txtResultados.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane1.setViewportView(txtResultados);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 120));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 170, 220, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtHora1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHora1KeyTyped
        
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            
            evt.consume();
        }
    }//GEN-LAST:event_txtHora1KeyTyped

    private void txtMinutos1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinutos1KeyTyped
        
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            
            evt.consume();
        }
    }//GEN-LAST:event_txtMinutos1KeyTyped

    private void txtSegundos1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundos1KeyTyped
        
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            
            evt.consume();
        }
    }//GEN-LAST:event_txtSegundos1KeyTyped

    private void txtHora2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHora2KeyTyped
        
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            
            evt.consume();
        }
    }//GEN-LAST:event_txtHora2KeyTyped

    private void txtMinutos2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinutos2KeyTyped
        
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            
            evt.consume();
        }
    }//GEN-LAST:event_txtMinutos2KeyTyped

    private void txtSegundos2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundos2KeyTyped
        
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            
            evt.consume();
        }

    }//GEN-LAST:event_txtSegundos2KeyTyped

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        if (txtHora1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el campo HORA de la hora 1, por favor");
            txtHora1.requestFocusInWindow();
        } else if (txtMinutos1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el campo MINUTOS de la hora 1, por favor");
            txtMinutos1.requestFocusInWindow();
        } else if (txtSegundos1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el campo SEGUNDOS de la hora 1, por favor");
            txtSegundos1.requestFocusInWindow();
        } else if (txtHora2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el campo HORA de la hora 2, por favor");
            txtHora2.requestFocusInWindow();
        } else if (txtMinutos2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el campo MINUTOs de la hora 2, por favor");
            txtMinutos2.requestFocusInWindow();
        } else if (txtSegundos2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el campo SEGUNDOS de la hora 2, por favor");
            txtSegundos2.requestFocusInWindow();
        } else {
            int h1, h2, m1, m2, s1, s2, op;
            
            h1 = Integer.parseInt(txtHora1.getText());
            h2 = Integer.parseInt(txtHora2.getText());
            m1 = Integer.parseInt(txtMinutos1.getText());
            m2 = Integer.parseInt(txtMinutos2.getText());
            s1 = Integer.parseInt(txtSegundos1.getText());
            s2 = Integer.parseInt(txtSegundos2.getText());
            
            hora1 = new Hora(h1, m1, s1);
            hora2 = new Hora(h2, m2, s2);
            
            cmdValidarHora1.setEnabled(true);
            cmdValidarHora2.setEnabled(true);
            cmdCompararHoras.setEnabled(true);
            
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdValidarHora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdValidarHora1ActionPerformed
        txtResultados.setText("");
        txtResultados.setText(hora1.validarHora1());
    }//GEN-LAST:event_cmdValidarHora1ActionPerformed

    private void cmdValidarHora2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdValidarHora2ActionPerformed
        txtResultados.setText("");
        txtResultados.setText(hora2.validarHora2());
    }//GEN-LAST:event_cmdValidarHora2ActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtHora1.setText("");
        txtHora2.setText("");
        txtMinutos1.setText("");
        txtMinutos2.setText("");
        txtSegundos1.setText("");
        txtSegundos2.setText("");
        txtResultados.setText("");

    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdCompararHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCompararHorasActionPerformed
        txtResultados.setText("");
        txtResultados.setText(hora1.compararHoras(hora2));
    }//GEN-LAST:event_cmdCompararHorasActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCompararHoras;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdValidarHora1;
    private javax.swing.JButton cmdValidarHora2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHora1;
    private javax.swing.JTextField txtHora2;
    private javax.swing.JTextField txtMinutos1;
    private javax.swing.JTextField txtMinutos2;
    private javax.swing.JTextArea txtResultados;
    private javax.swing.JTextField txtSegundos1;
    private javax.swing.JTextField txtSegundos2;
    // End of variables declaration//GEN-END:variables
}
